version: 2.1
setup: true
orbs:
  path-filtering: circleci/path-filtering@0.1.1
workflows:
  version: 2
  check-updated-files:
    jobs:
    - path-filtering/filter:
        mapping: |
          PowerShell\/(?!JumpCloud\sCommands\sGallery|JumpCloud\sOffice365\sSSO).* PowerShellModified true
        base-revision: master
        config-path: .circleci/workflows.yml